# Generated by Django 4.2.13 on 2026-07-01 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deadlines', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deadline',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deadline',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
