# Generated by Django 4.2.13 on 2026-07-08 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_picture_url',
            field=models.TextField(blank=True, help_text='URL or base64 data to user profile picture', null=True),
        ),
    ]
