# Generated by Django 4.2.13 on 2026-07-01 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lecture',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
